version: "3.8"
services:
  web1:
    image: html:web1
    build:
      context: .
      dockerfile: Dockerfile1
      container_name: shyamtest1
      ports:
        - "8000:80"

  web1:
    image: html:web2
    build:
      context: .
      dockerfile: Dockerfile1
      container_name: shyamtest1
      ports:
        - "8001:80"
      depends_on:
        - web1



  web1:
    image: html:web3
    build:
      context: .
      dockerfile: Dockerfile1
      container_name: shyamtest1
      ports:
        - "8002:80"
      depends_on:
        - web2
